### PR TITLE
Snapshot, typings, {N} 4.0 fixes, bump Native libs

### PR DESCRIPTION
**Pull request by DickSmith**
Make snapshot-friendly
Clean up TS, add full native typings
Update to latest Native packages
Breaking change {N} 4.0; `imageSource.setNative(x)` no longer returns boolean. (but the change here is backwards compatible).

### CODE REVIEW

**Comment by shiv19** [comment]
Thank you so much @DickSmith
Will release this in some time.

**Comment by shiv19** [comment]
@DickSmith 
I get 
```
* What went wrong:
A problem occurred configuring root project 'demo'.
> Could not resolve all dependencies for configuration ':_F0F1F2DebugApkCopy'.
   > Could not find com.android.support:appcompat-v7:27.1.0.
     Searched in the following locations:
         file:/Users/shiv19/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/27.1.0/appcompat-v7-27.1.0.pom
         file:/Users/shiv19/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/27.1.0/appcompat-v7-27.1.0.jar
         file:/Users/shiv19/Work/NsPlugins/nativescript-imagecropper/demo/platforms/android/sdk-manager/com/android/support/appcompat-v7/27.1.0/appcompat-v7-27.1.0.jar
     Required by:
         project :
         project : > com.android.support:design:26.0.0-alpha1
   > Could not find com.android.support:appcompat-v7:27.1.0.
     Searched in the following locations:
         file:/Users/shiv19/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/27.1.0/appcompat-v7-27.1.0.pom
         file:/Users/shiv19/Library/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/27.1.0/appcompat-v7-27.1.0.jar
         file:/Users/shiv19/Work/NsPlugins/nativescript-imagecropper/demo/platforms/android/sdk-manager/com/android/support/appcompat-v7/27.1.0/appcompat-v7-27.1.0.jar
     Required by:
         project :
         project : > com.github.yalantis:ucrop:2.2.2-native
```

When I try to run the demo. Can you please fix it?

**Comment by DickSmith** [comment]
@shiv19 
For sure, I'll take a look.

**Comment by shiv19** [comment]
@DickSmith Did you try running the demo, from the master branch?

**Comment by DickSmith** [comment]
@shiv19 Was just about to, last week was the end of a sprint here, so hadn't had time, but will look today.

**Pull request merged**
