### PR TITLE
fallback modal page looking behavior to v1.0.5

### PR DESCRIPTION
**Pull request by mailiam**
temporal falling back to previous behavior

addresses https://github.com/bthurlow/nativescript-imagecropper/issues/51#issuecomment-511568186

### CODE REVIEW

**Comment by shiv19** [comment]
Why not simply install 1.0.5 this is already published

**Comment by mailiam** [comment]
I don’t think that's friendly behavior to new users. Shouldn’t library just work after ‘tns plugin install’?

**Comment by shiv19** [comment]
your fix is right, thanks!

**Comment by shiv19** [comment]
Published 1.0.7

**Pull request merged**
