### PR TITLE
fix(ios): look through possible modal

### PR DESCRIPTION
**Pull request by mailiam**
iterate pages to find right view controller to present from

this PR fixes issue with modal pages.

### CODE REVIEW

**Comment by shiv19** [comment]
@mailiam Thanks for this PR <3

**Comment by mailiam** [comment]
> #106 the `const` should be changed to `let`

fixed with latest commit :]

**Comment by jannomeister** [comment]
@mailiam is it working on your side? :( maybe if this will merge ill test it again.

**Comment by mailiam** [comment]
@jannomeister OK I’m taking a look at it :)

**Comment by shiv19** [comment]
@mailiam 
Thank you for your contribution!
I've added your details to the contributor list :)

This was published as `nativescript-imagecropper@1.0.6`

**Comment by mailiam** [comment]
@shiv19 much appreciated :] 
hope to contribute furthermore

**Pull request merged**
