### PR TITLE
Adding support for webpack

### PR DESCRIPTION
**Pull request by Cayan**

### CODE REVIEW

**Comment by Cayan** [comment]
@shiv19 I've been working with version 0.0.7 of this plugin and it has been working properly with webpack

**Comment by shiv19** [comment]
@Cayan Today we were having a conversation regarding this with bradmartin, in the NS slack channel for plugins, removing the `.js` extension is actually required for it to work with webpack. I've faced this problem with the statusbar plugin as well. I'm trying to find @bthurlow on social media. do you have any lead?

**Comment by bthurlow** [comment]
What can I do for you @shiv19?

**Comment by bthurlow** [comment]
What can I help you with @shiv19?

**Comment by shiv19** [comment]
can you merge this pr? @bthurlow

**Comment by shiv19** [comment]
capture

We were talking about this on plugins channel in NS community slack

**Comment by bthurlow** [comment]
I merged and sent you a collab invite, I cannot build and release though as I'm no longer doing NS dev.

**Comment by shiv19** [comment]
sure, I'll take care of this 👍

**Comment by shiv19** [comment]
@bthurlow with your permission, I would like to refactor your plugin into the latest Nativescript plugin seed. 
https://github.com/NativeScript/nativescript-plugin-seed
this one

**Comment by bthurlow** [comment]
Sure.

**Comment by shiv19** [comment]
@bthurlow, and how to publish the plugin with your user name to npmjs?
I think you'll have to do the publishing part. I'll let you know when I finish doing this migration

**Comment by bthurlow** [comment]
Looks like I can add you to the project in npmjs.  Do you have a username I can send the invite too for npmjs?

**Comment by shiv19** [comment]
yes I do, my username on npmjs is `multishiv19 `

**Comment by bthurlow** [comment]
You should have access now.

**Comment by shiv19** [comment]
Yes. got it. Thanks a lot, @bthurlow  :D , and I got to learn many things from your code. It will surely help me build my next plugin :)

**Comment by shiv19** [comment]
Version 0.1.0 is now out! it supports latest {N} :)

**Comment by shiv19** [comment]
Also, now there is no longer need to declare the activity in the app's manifest file for android.
the plugin does this. :) @bthurlow

**Comment by shiv19** [comment]
Also, most of the issues have been closed :)

**Comment by shiv19** [comment]
@bthurlow please add me as a contributor to nativescript-maskedinput repo

**Comment by Cayan** [comment]
whoaa, lots of improvements here! I'm happy to see improvements in this plugin, it works great and there is also a lot to improve!

I've mentioned before that I had it working on my environment, there was a nasty post-build script to fix it on my project.

**Comment by Ablankzin** [comment]
Can I become a collaborator as well? I work with @Cayan  :)

**Pull request merged**
